-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 00:35:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catastro_turistico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `catastro_turistico` ;

-- -----------------------------------------------------
-- Schema catastro_turistico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catastro_turistico` DEFAULT CHARACTER SET utf8 ;
USE `catastro_turistico` ;

-- -----------------------------------------------------
-- Table `catastro_turistico`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`categorias` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`categorias` (
  `id_categoria` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`actividades` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`actividades` (
  `id_act` INT NOT NULL,
  `actividad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_act`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`sub_actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`sub_actividades` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`sub_actividades` (
  `id_sub_act` INT NOT NULL,
  `sub_actividad` VARCHAR(100) NOT NULL,
  `id_act` INT NOT NULL,
  PRIMARY KEY (`id_sub_act`),
  INDEX `fk_sub_actividades_idx` (`id_act` ASC) VISIBLE,
  CONSTRAINT `fk_sub_actividades`
    FOREIGN KEY (`id_act`)
    REFERENCES `catastro_turistico`.`actividades` (`id_act`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB ;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`contacto` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`contacto` (
  `id_contacto` INT NOT NULL,
  `correo` VARCHAR(150) NULL,
  `web` VARCHAR(100) NULL,
  `web_funcional` CHAR(2) NULL,
  `tel_principal` VARCHAR(20) NULL,
  `tel_secundario` VARCHAR(20) NULL,
  PRIMARY KEY (`id_contacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`provincias` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`provincias` (
  `cod_provincia` CHAR(2) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `poblacion` INT NULL,
  PRIMARY KEY (`cod_provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`climas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`climas` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`climas` (
  `cod_clima` CHAR(4) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_clima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`cantones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`cantones` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`cantones` (
  `cod_canton` CHAR(4) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `poblacion` INT NULL,
  `cod_provincias` CHAR(2) NOT NULL,
  `cod_clima` CHAR(4) NOT NULL,
  PRIMARY KEY (`cod_canton`),
  INDEX `fk_canton_prov_idx` (`cod_provincias` ASC) VISIBLE,
  UNIQUE INDEX `cod_prov_UNIQUE` (`cod_provincias` ASC, `nombre` ASC) INVISIBLE,
  INDEX `fk_climas_idx` (`cod_clima` ASC) INVISIBLE,
  CONSTRAINT `fk_canton_provincia`
    FOREIGN KEY (`cod_provincias`)
    REFERENCES `catastro_turistico`.`provincias` (`cod_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canton_climas`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `catastro_turistico`.`climas` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`parroquias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`parroquias` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`parroquias` (
  `cod_parroquias` CHAR(6) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `cod_canton` CHAR(4) NOT NULL,
  PRIMARY KEY (`cod_parroquias`),
  INDEX `fk_parroq_cant_idx` (`cod_canton` ASC) VISIBLE,
  CONSTRAINT `fk_parroquias_cantones`
    FOREIGN KEY (`cod_canton`)
    REFERENCES `catastro_turistico`.`cantones` (`cod_canton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`establecimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`establecimientos` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`establecimientos` (
  `id_estab` INT NOT NULL,
  `nombre_comercial` VARCHAR(200) NOT NULL,
  `direccion` VARCHAR(300) NULL,
  `referencia` VARCHAR(1000) NULL,
  `pet_friendly` CHAR(2) NULL,
  `puntuacion` VARCHAR(4) NULL,
  `id_sub_act` INT NOT NULL,
  `id_categoria_1` INT NOT NULL,
  `id_categoria_2` INT NULL,
  `id_contacto` INT NULL,
  `cod_parroquias` CHAR(6) NOT NULL,
  PRIMARY KEY (`id_estab`),
  INDEX `fk_estab_cat1_idx` (`id_categoria_1` ASC) VISIBLE,
  INDEX `fk_estab_cat2_idx` (`id_categoria_2` ASC) INVISIBLE,
  INDEX `fk_estab_sub_act_idx` (`id_sub_act` ASC) VISIBLE,
  INDEX `fk_estab_contacto_idx` (`id_contacto` ASC) VISIBLE,
  INDEX `fk_estab_parroquias_idx` (`cod_parroquias` ASC) VISIBLE,
  CONSTRAINT `fk_estab_cat1`
    FOREIGN KEY (`id_categoria_1`)
    REFERENCES `catastro_turistico`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estab_cat2`
    FOREIGN KEY (`id_categoria_2`)
    REFERENCES `catastro_turistico`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estab_sub_act`
    FOREIGN KEY (`id_sub_act`)
    REFERENCES `catastro_turistico`.`sub_actividades` (`id_sub_act`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estab_contacto`
    FOREIGN KEY (`id_contacto`)
    REFERENCES `catastro_turistico`.`contacto` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estab_parroquias`
    FOREIGN KEY (`cod_parroquias`)
    REFERENCES `catastro_turistico`.`parroquias` (`cod_parroquias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`clase_guia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`clase_guia` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`clase_guia` (
  `id_clase_guia` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_clase_guia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`guias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`guias` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`guias` (
  `id_guia` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `emision_licencia` DATE NOT NULL,
  `nacionalidad_1` VARCHAR(20) NOT NULL,
  `nacionalidad_2` VARCHAR(20) NULL,
  `cod_canton` CHAR(4) NOT NULL,
  `id_clase_guia` INT NOT NULL,
  PRIMARY KEY (`id_guia`),
  INDEX `fk_guia_canton_idx` (`cod_canton` ASC) VISIBLE,
  INDEX `fk_clase_guia_idx` (`id_clase_guia` ASC) VISIBLE,
  CONSTRAINT `fk_guia_canton`
    FOREIGN KEY (`cod_canton`)
    REFERENCES `catastro_turistico`.`cantones` (`cod_canton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_guia`
    FOREIGN KEY (`id_clase_guia`)
    REFERENCES `catastro_turistico`.`clase_guia` (`id_clase_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`idiomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`idiomas` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`idiomas` (
  `cod_idioma` CHAR(2) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_idioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`idioma_habla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`idioma_habla` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`idioma_habla` (
  `id_guia` INT NOT NULL,
  `cod_idioma` CHAR(2) NOT NULL,
  INDEX `fk_idioma_guia_idx` (`id_guia` ASC) VISIBLE,
  INDEX `fk_habla_idioma_idx` (`cod_idioma` ASC) VISIBLE,
  UNIQUE INDEX `id_guia_UNIQUE` (`id_guia` ASC, `cod_idioma` ASC) VISIBLE,
  CONSTRAINT `fk_guia`
    FOREIGN KEY (`id_guia`)
    REFERENCES `catastro_turistico`.`guias` (`id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idiomas`
    FOREIGN KEY (`cod_idioma`)
    REFERENCES `catastro_turistico`.`idiomas` (`cod_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro_turistico`.`capacidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_turistico`.`capacidad` ;

CREATE TABLE IF NOT EXISTS `catastro_turistico`.`capacidad` (
  `id_capacidad` INT NOT NULL,
  `habitaciones` INT NOT NULL,
  `camas` INT NOT NULL,
  `id_sub_act` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `cod_canton` CHAR(4) NOT NULL,
  PRIMARY KEY (`id_capacidad`),
  INDEX `fk_cap_sub_act_idx` (`id_sub_act` ASC) VISIBLE,
  INDEX `fk_cap_cat_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_cap_canton_idx` (`cod_canton` ASC) VISIBLE,
  CONSTRAINT `fk_cap_sub_act`
    FOREIGN KEY (`id_sub_act`)
    REFERENCES `catastro_turistico`.`sub_actividades` (`id_sub_act`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cap_cat`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `catastro_turistico`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cap_canton`
    FOREIGN KEY (`cod_canton`)
    REFERENCES `catastro_turistico`.`cantones` (`cod_canton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data Insertion
-- -----------------------------------------------------
-- categrias
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/categorias.csv'
  INTO TABLE categorias 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- actividades
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/actividades.csv'
  INTO TABLE actividades 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- sub_actividades
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/sub_actividades.csv'
  INTO TABLE sub_actividades 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- contacto
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/contacto.csv'
  INTO TABLE contacto 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- provincias
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/provincias.csv'
  INTO TABLE provincias 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- climas
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/climas.csv'
  INTO TABLE climas 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- cantones
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/cantones.csv'
  INTO TABLE cantones 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- parroquias
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/parroquias.csv'
  INTO TABLE parroquias 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- establecimientos
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/establecimientos.csv'
  INTO TABLE establecimientos 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- clase_guias
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/clase_guia.csv'
  INTO TABLE clase_guia 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- guias
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/guias.csv'
  INTO TABLE guias 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- idiomas
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/idiomas.csv'
  INTO TABLE idiomas 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- idiomas_habla
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/idioma_habla.csv'
  INTO TABLE idioma_habla 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- capacidad
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/capacidad.csv'
  INTO TABLE capacidad 
  FIELDS TERMINATED BY '|'
  ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  IGNORE 1 LINES;

-- -----------------------------------------------------
-- Create USER
-- -----------------------------------------------------

CREATE USER grupo_a@localhost IDENTIFIED BY 'grupoa';
GRANT SELECT ON catastro_turistico.* to grupo_a@localhost;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
